name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with the full history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Configure Git for commits
      - name: Configure Git
        run: |
          git config user.name "28p07"
          git config user.email "sharmapuneet8126@gmail.com"

      # Pull the latest changes with rebase
      - name: Pull and Rebase from Remote
        id: pull_step
        continue-on-error: true  # Allow workflow to continue even if pull fails
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull --rebase https://28p07:$HF_TOKEN@huggingface.co/spaces/28p07/yt_web_summarizer main

      # Handle conflicts if they arise
      - name: Resolve Merge Conflicts (Auto-Resolve with Remote Changes)
        if: failure() && contains(steps.pull_step.outputs.stdout, 'Merge conflict')
        run: |
          git checkout --theirs .
          git add .
          git rebase --continue || echo "Rebase completed with conflicts resolved."

      # Abort rebase if conflicts are unresolved
      - name: Abort Rebase if Needed
        if: failure()
        run: git rebase --abort

      # Force Push Resolved Changes
      - name: Force Push to Hugging Face
        if: success() || always()  # Ensure push happens after resolving or aborting conflicts
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://28p07:$HF_TOKEN@huggingface.co/spaces/28p07/yt_web_summarizer main
