name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config user.name "28p07"
          git config user.email "sharmapuneet8126@gmai.com"

      - name: Pull latest changes with rebase
        continue-on-error: true
        run: |
          git pull https://28p07:$HF_TOKEN@huggingface.co/spaces/28p07/yt_web_summarizer main --rebase

      - name: Resolve conflict (keep remote changes)
        if: failure() && contains(steps.pull.outputs.stdout, 'Merge conflict')
        run: |
          git checkout --theirs README.md
          git add README.md
          git rebase --continue

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://28p07:$HF_TOKEN@huggingface.co/spaces/28p07/yt_web_summarizer main
